import type {
  AgentTask,
  EventLog,
  Message,
  MessageRole,
  Session,
  SessionStatus,
  SwarmMessage,
  SwarmState,
  SwarmTeammate,
  SwarmThread,
  SwarmWaitingEdge,
} from './types';
import type {
  RuntimeEvent,
  RuntimeMessageSummary,
  RuntimeRawMessage,
  RuntimeRegistryEvent,
  RuntimeSessionDetail,
  RuntimeSessionSnapshot,
  RuntimeSessionStatus,
  RuntimeSwarmTeammateSummary,
  RuntimeSwarmThreadSummary,
  RuntimeSwarmWaitingEdge,
  RuntimeTaskSummary,
} from './runtime-protocol';

const AVATAR_COLORS = ['#6366f1', '#8b5cf6', '#10b981', '#f59e0b', '#ec4899', '#3b82f6'];
const SWARM_COLOR_MAP: Record<string, string> = {
  slate: '#64748b',
  gray: '#6b7280',
  zinc: '#71717a',
  neutral: '#737373',
  stone: '#78716c',
  red: '#ef4444',
  orange: '#f97316',
  amber: '#f59e0b',
  yellow: '#eab308',
  lime: '#84cc16',
  green: '#22c55e',
  emerald: '#10b981',
  teal: '#14b8a6',
  cyan: '#06b6d4',
  sky: '#0ea5e9',
  blue: '#3b82f6',
  indigo: '#6366f1',
  violet: '#8b5cf6',
  purple: '#a855f7',
  fuchsia: '#d946ef',
  pink: '#ec4899',
  rose: '#f43f5e',
};
const STREAMING_ASSISTANT_PREFIX = 'streaming-assistant-';
const STREAMING_THINKING_PREFIX = 'streaming-thinking-';

function getBasename(path: string): string {
  const normalized = path.replace(/\\/g, '/').replace(/\/+$/, '');
  const segments = normalized.split('/');
  return segments[segments.length - 1] || path;
}

function mapRuntimeStatus(status: RuntimeSessionStatus): SessionStatus {
  switch (status) {
    case 'running':
      return 'running';
    case 'requires_action':
      return 'waiting';
    case 'completed':
      return 'completed';
    case 'errored':
      return 'error';
    default:
      return 'idle';
  }
}

function formatModel(model: string | null | undefined): string {
  return model?.trim() || 'auto';
}

function stripKnownCommandMarkup(text: string): string {
  const commandName = text.match(/<command-name>([\s\S]*?)<\/command-name>/i)?.[1]?.trim();
  const commandArgs = text.match(/<command-args>([\s\S]*?)<\/command-args>/i)?.[1]?.trim();

  if (commandName) {
    return [commandName, commandArgs].filter(Boolean).join(' ').trim();
  }

  const inlineCommand = text.match(/<command-message>([\s\S]*?)<\/command-message>/i)?.[1]?.trim();
  if (inlineCommand) {
    return inlineCommand;
  }

  return text;
}

function stripGenericTags(text: string): string {
  if (!/^<[\s\S]+>$/.test(text.trim())) {
    return text;
  }

  return text.replace(/<\/?[^>]+>/g, ' ').replace(/\s+/g, ' ').trim();
}

export function sanitizeRuntimeTranscript(text: string): {
  text: string;
  hidden: boolean;
} {
  let next = text.trim();

  if (!next) {
    return { text: '', hidden: true };
  }

  if (/<local-command-caveat>/i.test(next)) {
    return { text: '', hidden: true };
  }

  if (/<local-command-(stdout|stderr)>/i.test(next)) {
    return { text: '', hidden: true };
  }

  next = stripKnownCommandMarkup(next);
  next = next.replace(/<internal_thinking>[\s\S]*?<\/internal_thinking>/gi, '').trim();
  next = next
    .split('\n')
    .filter(line => !/^\[(thinking|redacted_thinking)\]$/i.test(line.trim()))
    .filter(line => !/^\[[a-z_]+]$/i.test(line.trim()) || /\s/.test(line.trim()))
    .join('\n')
    .trim();

  if (!next) {
    return { text: '', hidden: true };
  }

  if (/^Caveat: The messages below were generated by the user while running local commands\./i.test(next)) {
    return { text: '', hidden: true };
  }

  next = stripGenericTags(next);

  if (!next) {
    return { text: '', hidden: true };
  }

  return { text: next, hidden: false };
}

function summarizeUnknownContent(content: unknown): string {
  if (typeof content === 'string') {
    return content;
  }

  if (!Array.isArray(content)) {
    return '';
  }

  return content
    .map(block => {
      if (typeof block === 'string') {
        return block;
      }

      if (!block || typeof block !== 'object') {
        return '';
      }

      const candidate = block as {
        type?: unknown;
        text?: unknown;
        thinking?: unknown;
      };

      if (typeof candidate.text === 'string') {
        return candidate.text;
      }

      if (typeof candidate.thinking === 'string') {
        return '[thinking]';
      }

      if (typeof candidate.type === 'string') {
        return `[${candidate.type}]`;
      }

      return '';
    })
    .filter(Boolean)
    .join('\n')
    .trim();
}

function resolveRawMessageText(message: RuntimeRawMessage): string {
  if (message.type === 'user' || message.type === 'assistant') {
    return summarizeUnknownContent(message.message?.content);
  }

  if (message.type === 'system') {
    return message.content || '';
  }

  if (message.type === 'attachment') {
    return (
      message.attachment?.message ||
      message.attachment?.stdout ||
      message.attachment?.stderr ||
      message.attachment?.command ||
      ''
    );
  }

  if (message.type === 'progress') {
    return typeof message.data === 'string'
      ? message.data
      : JSON.stringify(message.data ?? {});
  }

  return message.content || '';
}

function normalizeMessageRole(type: string): MessageRole {
  if (type === 'user' || type === 'assistant' || type === 'system') {
    return type;
  }

  return 'system';
}

function buildMessage(params: {
  id: string;
  role: MessageRole;
  content: string;
  timestamp: string;
  isHiddenInternally?: boolean;
  isPending?: boolean;
  isEphemeral?: boolean;
  label?: string;
  streamKind?: 'thinking' | 'response';
}): Message {
  return {
    id: params.id,
    role: params.role,
    content: params.content,
    timestamp: params.timestamp,
    isHiddenInternally: params.isHiddenInternally,
    isPending: params.isPending,
    isEphemeral: params.isEphemeral,
    label: params.label,
    streamKind: params.streamKind,
  };
}

function normalizeMessageContent(content: string): string {
  return content.replace(/\s+/g, ' ').trim();
}

function shouldReplacePendingMessage(
  pending: Message,
  nextMessage: Message,
): boolean {
  if (!pending.isPending) {
    return false;
  }

  if (nextMessage.role === 'assistant') {
    return (
      pending.role === 'assistant' &&
      pending.streamKind === 'response' &&
      pending.id.startsWith(STREAMING_ASSISTANT_PREFIX)
    );
  }

  return (
    pending.role === nextMessage.role &&
    normalizeMessageContent(pending.content) ===
      normalizeMessageContent(nextMessage.content)
  );
}

export function mapRuntimeMessageSummaryToUi(
  message: RuntimeMessageSummary,
): Message | null {
  const sanitized = sanitizeRuntimeTranscript(message.text);
  if (message.isMeta || sanitized.hidden) {
    return null;
  }

  return buildMessage({
    id: message.uuid,
    role: normalizeMessageRole(message.type),
    content: sanitized.text,
    timestamp: message.timestamp,
    label: message.label,
  });
}

export function mapRawRuntimeMessageToUi(message: RuntimeRawMessage): Message | null {
  if (message.isMeta) {
    return null;
  }

  const sanitized = sanitizeRuntimeTranscript(resolveRawMessageText(message));
  if (sanitized.hidden) {
    return null;
  }

  return buildMessage({
    id: message.uuid,
    role: normalizeMessageRole(message.type),
    content: sanitized.text,
    timestamp: message.timestamp,
    label: message.subtype || message.type,
  });
}

function mapTaskStatus(status: string): AgentTask['status'] {
  const normalized = status.trim().toLowerCase();
  if (
    normalized === 'active' ||
    normalized === 'running' ||
    normalized === 'in_progress'
  ) {
    return 'active';
  }

  if (
    normalized === 'completed' ||
    normalized === 'done' ||
    normalized === 'success'
  ) {
    return 'completed';
  }

  if (normalized === 'failed' || normalized === 'error' || normalized === 'errored') {
    return 'failed';
  }

  return 'pending';
}

function inferTeammateRole(name: string, index: number): string {
  const normalized = name.toLowerCase();
  if (normalized.includes('qa') || normalized.includes('test')) {
    return 'QA Agent';
  }
  if (normalized.includes('design')) {
    return 'Design Agent';
  }
  if (normalized.includes('search') || normalized.includes('research')) {
    return 'Research Agent';
  }
  if (normalized.includes('edit') || normalized.includes('code')) {
    return 'Code Agent';
  }
  return index === 0 ? 'Lead Agent' : 'AI Agent';
}

function formatAgentType(agentType: string | undefined): string | undefined {
  if (!agentType?.trim()) {
    return undefined;
  }

  return agentType
    .trim()
    .split(/[_-\s]+/)
    .filter(Boolean)
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

function resolveSwarmColor(color: string | undefined, index: number): string {
  if (!color?.trim()) {
    return AVATAR_COLORS[index % AVATAR_COLORS.length];
  }

  const normalized = color.trim().toLowerCase();
  if (
    normalized.startsWith('#') ||
    normalized.startsWith('rgb(') ||
    normalized.startsWith('rgba(') ||
    normalized.startsWith('hsl(') ||
    normalized.startsWith('hsla(')
  ) {
    return color;
  }

  return SWARM_COLOR_MAP[normalized] || AVATAR_COLORS[index % AVATAR_COLORS.length];
}

function createFallbackTeammateSummary(
  name: string,
  index: number,
): RuntimeSwarmTeammateSummary {
  return {
    id: `teammate-${index}-${name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`,
    name,
  };
}

function participantMatches(
  candidate: string | undefined,
  teammate: RuntimeSwarmTeammateSummary,
): boolean {
  if (!candidate) {
    return false;
  }

  return candidate === teammate.id || candidate === teammate.name;
}

function mapTasks(
  tasks: RuntimeTaskSummary[],
  teammates: RuntimeSwarmTeammateSummary[],
): AgentTask[] {
  return tasks.map(task => {
    const assignee = teammates.find(teammate =>
      participantMatches(task.owner || task.assigneeName, teammate),
    );

    return {
      id: task.id,
      description:
        task.title?.trim() ||
        task.kind?.trim() ||
        `Task ${task.id.slice(0, 8)}`,
      status: mapTaskStatus(task.status),
      assigneeId: assignee?.id,
      assigneeName: assignee?.name || task.assigneeName || task.owner,
      kind: task.kind?.trim() || undefined,
    };
  });
}

function mapThreads(threads: RuntimeSwarmThreadSummary[]): SwarmThread[] {
  return threads.map(thread => ({
    id: thread.threadId,
    topic: thread.topic,
    participants: thread.participants,
    lastKind: thread.lastKind,
    lastAt: thread.lastAt,
    lastBody: thread.lastBody,
    open: thread.open,
  }));
}

function mapWaitingEdges(edges: RuntimeSwarmWaitingEdge[]): SwarmWaitingEdge[] {
  return edges.map(edge => ({
    id: edge.eventId,
    threadId: edge.threadId,
    topic: edge.topic,
    from: edge.from,
    to: edge.to,
    body: edge.body,
    createdAt: edge.createdAt,
  }));
}

function mapInternalChat(
  threads: RuntimeSwarmThreadSummary[],
  teammates: SwarmTeammate[],
): SwarmMessage[] {
  const teammateMap = new Map(teammates.map(teammate => [teammate.name, teammate]));

  return [...threads]
    .sort((left, right) => Date.parse(left.lastAt) - Date.parse(right.lastAt))
    .slice(-12)
    .map(thread => {
      const fromName = thread.waitingOn?.from || thread.participants[0] || 'Swarm';
      const toName = thread.waitingOn?.to || thread.participants[1];

      return {
        id: thread.threadId,
        fromId: teammateMap.get(fromName)?.id || fromName,
        fromName,
        toId: toName ? teammateMap.get(toName)?.id || toName : undefined,
        toName,
        content: thread.lastBody,
        timestamp: thread.lastAt,
      };
    });
}

function createSwarmState(
  snapshot: RuntimeSessionSnapshot,
  tasks: RuntimeTaskSummary[],
  threads: RuntimeSwarmThreadSummary[],
  waitingEdges: RuntimeSwarmWaitingEdge[],
): SwarmState | undefined {
  const hasSwarm =
    Boolean(snapshot.swarm.teamName) ||
    snapshot.swarm.teammateNames.length > 0 ||
    tasks.length > 0 ||
    threads.length > 0 ||
    waitingEdges.length > 0;

  if (!hasSwarm) {
    return undefined;
  }

  const runtimeTeammates =
    snapshot.swarm.teammates.length > 0
      ? snapshot.swarm.teammates
      : snapshot.swarm.teammateNames.map(createFallbackTeammateSummary);

  const mappedTasks = mapTasks(tasks, runtimeTeammates);
  const teammates = runtimeTeammates.map((teammate, index) => {
    const assignedTasks = mappedTasks.filter(task => task.assigneeId === teammate.id);
    const activeAssignedTask = assignedTasks.find(task => task.status === 'active');
    const pendingAssignedTask = assignedTasks.find(task => task.status === 'pending');
    const latestIncomingEdge = waitingEdges.find(edge => participantMatches(edge.to, teammate));
    const latestOutgoingEdge = waitingEdges.find(edge => participantMatches(edge.from, teammate));
    const latestThread = threads.find(thread =>
      thread.participants.some(participant => participantMatches(participant, teammate)),
    );

    let status: SwarmTeammate['status'] = 'idle';
    let statusDetail: string | undefined;

    if (latestIncomingEdge) {
      status = 'speaking';
      statusDetail = `Needs response to ${latestIncomingEdge.from}`;
    } else if (latestOutgoingEdge) {
      status = 'waiting';
      statusDetail = `Waiting on ${latestOutgoingEdge.to}`;
    } else if (activeAssignedTask || pendingAssignedTask || latestThread?.open) {
      status = 'working';
      statusDetail = activeAssignedTask
        ? 'Executing assigned task'
        : pendingAssignedTask
          ? 'Assigned task queued'
          : latestThread?.topic?.trim()
            ? `Open thread: ${latestThread.topic.trim()}`
            : 'Active in swarm';
    }

    const currentInstruction =
      latestIncomingEdge?.body?.trim() ||
      (latestThread &&
      ['task', 'handoff', 'question'].includes(latestThread.lastKind) &&
      latestThread.lastBody.trim()
        ? latestThread.lastBody.trim()
        : undefined);

    return {
      id: teammate.id,
      name: teammate.name,
      role: formatAgentType(teammate.agentType) || inferTeammateRole(teammate.name, index),
      status,
      avatarColor: resolveSwarmColor(teammate.color, index),
      currentTask:
        activeAssignedTask?.description ||
        pendingAssignedTask?.description ||
        latestThread?.topic?.trim() ||
        undefined,
      currentInstruction,
      statusDetail,
      threadTopic: latestThread?.topic?.trim() || undefined,
      workspace: teammate.worktreePath?.trim() || teammate.cwd?.trim() || undefined,
    };
  }) satisfies SwarmTeammate[];

  return {
    activeTeam: snapshot.swarm.teamName || 'Swarm',
    teammates,
    tasks: mappedTasks,
    waitingOn:
      waitingEdges[0]
        ? `${waitingEdges[0].from} -> ${waitingEdges[0].to}`
        : undefined,
    internalChat: mapInternalChat(threads, teammates),
    threads: mapThreads(threads),
    waitingEdges: mapWaitingEdges(waitingEdges),
  };
}

function createBaseSession(
  snapshot: RuntimeSessionSnapshot,
  previous?: Session,
  updatedAt?: string,
): Session {
  const timestamp = updatedAt || new Date().toISOString();
  const swarm = createSwarmState(snapshot, [], [], []);

  return {
    id: snapshot.sessionId,
    shortId: snapshot.sessionId.slice(0, 8),
    projectName: getBasename(snapshot.cwd),
    title: previous?.title || snapshot.sessionId.slice(0, 8),
    workspaceName: snapshot.cwd,
    status: mapRuntimeStatus(snapshot.status),
    activeChannel: snapshot.activeChannel,
    activeChannelUpdatedAt: snapshot.activeChannelUpdatedAt,
    permissionMode: snapshot.permissionMode,
    isBypassPermissionsModeAvailable: snapshot.isBypassPermissionsModeAvailable,
    isAutoModeAvailable: snapshot.isAutoModeAvailable,
    model: formatModel(snapshot.mainLoopModelForSession || snapshot.mainLoopModel),
    messages: previous?.messages || [],
    swarm: previous?.swarm || swarm,
    events: previous?.events || [],
    startedAt: previous?.startedAt || timestamp,
    updatedAt: timestamp,
    archived: previous?.archived || false,
    messageCount: snapshot.messageCount,
    taskCount: snapshot.taskCount,
    rawSnapshot: snapshot,
    rawDetail: previous?.rawDetail,
  };
}

function sortSessions(sessions: Session[]): Session[] {
  return [...sessions].sort(
    (left, right) => Date.parse(right.updatedAt) - Date.parse(left.updatedAt),
  );
}

export function mergeSnapshotsIntoSessions(
  previousSessions: Session[],
  snapshots: RuntimeSessionSnapshot[],
  updatedAt?: string,
): Session[] {
  const previousMap = new Map(previousSessions.map(session => [session.id, session]));

  const merged = snapshots.map(snapshot =>
    createBaseSession(snapshot, previousMap.get(snapshot.sessionId), updatedAt),
  );

  return sortSessions(merged);
}

export function applyDetailToSession(
  previousSession: Session | undefined,
  detail: RuntimeSessionDetail,
): Session {
  const base = createBaseSession(
    detail.snapshot,
    previousSession,
    detail.messages[detail.messages.length - 1]?.timestamp || new Date().toISOString(),
  );
  const messages = detail.messages
    .map(mapRuntimeMessageSummaryToUi)
    .filter((message): message is Message => message !== null);
  const pendingMessages =
    previousSession?.messages.filter(message => message.isPending) || [];
  const mergedMessages = [...messages];
  const shouldPreserveAssistantPending =
    detail.snapshot.status === 'running' ||
    detail.snapshot.status === 'requires_action';

  for (const pendingMessage of pendingMessages) {
    if (mergedMessages.some(message => message.id === pendingMessage.id)) {
      continue;
    }

    if (pendingMessage.role === 'assistant') {
      if (!shouldPreserveAssistantPending) {
        continue;
      }

      if (pendingMessage.streamKind === 'thinking') {
        mergedMessages.push(pendingMessage);
        continue;
      }

      const hasMatchingAssistantMessage = mergedMessages.some(
        message =>
          message.role === 'assistant' &&
          !message.isPending &&
          normalizeMessageContent(message.content) ===
            normalizeMessageContent(pendingMessage.content),
      );

      if (!hasMatchingAssistantMessage) {
        mergedMessages.push(pendingMessage);
      }
      continue;
    }

    if (pendingMessage.role === 'user') {
      const hasMatchingUserMessage = mergedMessages.some(
        message =>
          message.role === 'user' &&
          normalizeMessageContent(message.content) ===
            normalizeMessageContent(pendingMessage.content),
      );

      if (!hasMatchingUserMessage) {
        mergedMessages.push(pendingMessage);
      }
      continue;
    }

    mergedMessages.push(pendingMessage);
  }

  mergedMessages.sort(
    (left, right) => Date.parse(left.timestamp) - Date.parse(right.timestamp),
  );

  return {
    ...base,
    messages: mergedMessages,
    swarm: createSwarmState(
      detail.snapshot,
      detail.tasks,
      detail.swarmThreads,
      detail.swarmWaitingEdges,
    ),
    rawDetail: detail,
  };
}

export function mergeDetailIntoSessions(
  previousSessions: Session[],
  detail: RuntimeSessionDetail,
): Session[] {
  const sessionMap = new Map(previousSessions.map(session => [session.id, session]));
  sessionMap.set(
    detail.snapshot.sessionId,
    applyDetailToSession(sessionMap.get(detail.snapshot.sessionId), detail),
  );
  return sortSessions([...sessionMap.values()]);
}

export function createOptimisticUserMessage(text: string): Message {
  return buildMessage({
    id: `pending-${crypto.randomUUID()}`,
    role: 'user',
    content: text,
    timestamp: new Date().toISOString(),
    isPending: true,
    label: 'user',
  });
}

function createStreamingThinkingMessage(
  sessionId: string,
  content: string,
  timestamp: string,
): Message {
  return buildMessage({
    id: `${STREAMING_THINKING_PREFIX}${sessionId}`,
    role: 'assistant',
    content: content || 'Pensando...',
    timestamp,
    isPending: true,
    isEphemeral: true,
    label: 'assistant:thinking',
    streamKind: 'thinking',
  });
}

function createStreamingAssistantMessage(
  sessionId: string,
  content: string,
  timestamp: string,
): Message {
  return buildMessage({
    id: `${STREAMING_ASSISTANT_PREFIX}${sessionId}`,
    role: 'assistant',
    content: content || '',
    timestamp,
    isPending: true,
    isEphemeral: true,
    label: 'assistant:stream',
    streamKind: 'response',
  });
}

export function appendMessageToSession(
  previousSessions: Session[],
  sessionId: string,
  message: Message,
): Session[] {
  return sortSessions(
    previousSessions.map(session => {
      if (session.id !== sessionId) {
        return session;
      }

      if (session.messages.some(existing => existing.id === message.id)) {
        return session;
      }

      const keptMessages = session.messages.filter(existing => {
        if (message.role === 'assistant' && existing.isPending && existing.role === 'assistant') {
          if (existing.streamKind === 'thinking') {
            return false;
          }
        }

        return !shouldReplacePendingMessage(existing, message);
      });
      const assistantPendingMessages =
        message.role === 'user'
          ? keptMessages.filter(
              existing => existing.isPending && existing.role === 'assistant',
            )
          : [];
      const nonAssistantPendingMessages =
        message.role === 'user'
          ? keptMessages.filter(
              existing => !(existing.isPending && existing.role === 'assistant'),
            )
          : keptMessages;

      return {
        ...session,
        messages:
          message.role === 'user'
            ? [
                ...nonAssistantPendingMessages,
                message,
                ...assistantPendingMessages,
              ]
            : [...keptMessages, message],
        messageCount: Math.max(session.messageCount, session.messages.length + 1),
        updatedAt: message.timestamp,
        status: message.role === 'assistant' ? 'running' : session.status,
      };
    }),
  );
}

function upsertStreamingMessage(
  previousSessions: Session[],
  sessionId: string,
  options: {
    streamKind: 'thinking' | 'response';
    delta: string;
    timestamp: string;
  },
): Session[] {
  const streamingId =
    options.streamKind === 'thinking'
      ? `${STREAMING_THINKING_PREFIX}${sessionId}`
      : `${STREAMING_ASSISTANT_PREFIX}${sessionId}`;
  const createMessage =
    options.streamKind === 'thinking'
      ? createStreamingThinkingMessage
      : createStreamingAssistantMessage;

  return sortSessions(
    previousSessions.map(session => {
      if (session.id !== sessionId) {
        return session;
      }

      const existing = session.messages.find(message => message.id === streamingId);
      if (existing) {
        return {
          ...session,
          messages: session.messages.map(message =>
            message.id === streamingId
              ? {
                  ...message,
                  content: `${message.content === 'Pensando...' ? '' : message.content}${options.delta}`,
                  timestamp: options.timestamp,
                }
              : message,
          ),
          updatedAt: options.timestamp,
          status: 'running',
        };
      }

      return {
        ...session,
        messages: [
          ...session.messages,
          createMessage(sessionId, options.delta, options.timestamp),
        ],
        updatedAt: options.timestamp,
        status: 'running',
      };
    }),
  );
}

function ensureStreamingThinkingPlaceholder(
  previousSessions: Session[],
  sessionId: string,
  timestamp: string,
): Session[] {
  const streamingId = `${STREAMING_THINKING_PREFIX}${sessionId}`;

  return sortSessions(
    previousSessions.map(session => {
      if (session.id !== sessionId) {
        return session;
      }

      const existing = session.messages.find(message => message.id === streamingId);
      if (existing || session.messages.some(message => message.streamKind === 'response' && message.isPending)) {
        return {
          ...session,
          updatedAt: timestamp,
          status: 'running',
        };
      }

      return {
        ...session,
        messages: [
          ...session.messages,
          createStreamingThinkingMessage(sessionId, 'Pensando...', timestamp),
        ],
        updatedAt: timestamp,
        status: 'running',
      };
    }),
  );
}

function clearStreamingMessage(
  previousSessions: Session[],
  sessionId: string,
  streamKind: 'thinking' | 'response',
): Session[] {
  return sortSessions(
    previousSessions.map(session => {
      if (session.id !== sessionId) {
        return session;
      }

      return {
        ...session,
        messages: session.messages.filter(
          message => !(message.isPending && message.streamKind === streamKind),
        ),
      };
    }),
  );
}

function clearPendingMessagesFromSession(
  previousSessions: Session[],
  sessionId: string,
): Session[] {
  return sortSessions(
    previousSessions.map(session =>
      session.id === sessionId
        ? {
            ...session,
            messages: session.messages.filter(message => !message.isPending),
          }
        : session,
    ),
  );
}

export function appendOptimisticMessage(
  previousSessions: Session[],
  sessionId: string,
  text: string,
): Session[] {
  const optimistic = createOptimisticUserMessage(text);

  return sortSessions(
    previousSessions.map(session =>
      session.id === sessionId
        ? {
            ...session,
            messages: [
              ...session.messages.filter(
                message => !(message.streamKind === 'thinking' && message.isPending),
              ),
              optimistic,
              ...(!session.messages.some(
                message =>
                  message.streamKind === 'response' && message.isPending,
              )
                ? [
                    createStreamingThinkingMessage(
                      sessionId,
                      'Pensando...',
                      optimistic.timestamp,
                    ),
                  ]
                : []),
            ],
            messageCount: session.messageCount + 1,
            updatedAt: optimistic.timestamp,
            status: session.status === 'idle' ? 'running' : session.status,
          }
        : session,
    ),
  );
}

function createEventLog(
  id: string,
  type: EventLog['type'],
  message: string,
  timestamp: string,
): EventLog {
  return { id, type, message, timestamp };
}

function createSystemRuntimeMessage(
  sessionId: string,
  content: string,
  timestamp: string,
): Message {
  return buildMessage({
    id: `system-${sessionId}-${timestamp}-${content.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`,
    role: 'system',
    content,
    timestamp,
    label: 'system',
  });
}

function summarizeTaskRuntimeLabel(task: RuntimeTaskSummary): string {
  return task.title?.trim() || task.kind?.trim() || `Task ${task.id.slice(0, 8)}`;
}

function formatOwnerSuffix(owner?: string): string {
  const trimmedOwner = owner?.trim();
  return trimmedOwner ? ` @${trimmedOwner}` : '';
}

function eventLogFromRuntimeEvent(event: RuntimeEvent): EventLog | null {
  switch (event.type) {
    case 'session_started':
      return createEventLog(
        `session-started-${event.sessionId}-${event.timestamp}`,
        'info',
        'Session started.',
        event.timestamp,
      );
    case 'session_updated':
      return null;
    case 'task_updated':
      return createEventLog(
        `task-updated-${event.sessionId}-${event.task.id}-${event.timestamp}`,
        event.task.status.toLowerCase().includes('fail') ? 'error' : 'info',
        `${event.task.title || event.task.kind || 'Task'} → ${event.task.status}`,
        event.timestamp,
      );
    case 'task_started':
      return createEventLog(
        `task-started-${event.sessionId}-${event.payload.task.id}-${event.timestamp}`,
        'info',
        `Task started: ${summarizeTaskRuntimeLabel(event.payload.task)}${formatOwnerSuffix(
          event.payload.task.assigneeName || event.payload.task.owner,
        )}.`,
        event.timestamp,
      );
    case 'task_progress':
      return createEventLog(
        `task-progress-${event.sessionId}-${event.payload.task.id}-${event.timestamp}`,
        'info',
        event.payload.progressText?.trim() ||
          event.payload.summary?.trim() ||
          `Task in progress: ${summarizeTaskRuntimeLabel(event.payload.task)}${formatOwnerSuffix(
            event.payload.task.assigneeName || event.payload.task.owner,
          )}.`,
        event.timestamp,
      );
    case 'task_completed':
      return createEventLog(
        `task-completed-${event.sessionId}-${event.payload.task.id}-${event.timestamp}`,
        event.payload.task.status.toLowerCase().includes('fail') ? 'error' : 'info',
        event.payload.summary?.trim() ||
          `Task completed: ${summarizeTaskRuntimeLabel(event.payload.task)}${formatOwnerSuffix(
            event.payload.task.assigneeName || event.payload.task.owner,
          )}.`,
        event.timestamp,
      );
    case 'tool_started':
      return createEventLog(
        `tool-started-${event.sessionId}-${event.payload.toolUseId}-${event.timestamp}`,
        'info',
        `Tool started: ${event.payload.toolName}${
          event.payload.taskId ? ` · task ${event.payload.taskId}` : ''
        }.`,
        event.timestamp,
      );
    case 'tool_progress':
      return createEventLog(
        `tool-progress-${event.sessionId}-${event.payload.toolUseId}-${event.timestamp}`,
        'info',
        event.payload.summary?.trim() ||
          `Tool running: ${event.payload.toolName}.`,
        event.timestamp,
      );
    case 'tool_completed':
      return createEventLog(
        `tool-completed-${event.sessionId}-${event.payload.toolUseId}-${event.timestamp}`,
        'info',
        event.payload.summary?.trim() ||
          `Tool completed: ${event.payload.toolName}.`,
        event.timestamp,
      );
    case 'swarm_updated':
      return createEventLog(
        `swarm-updated-${event.sessionId}-${event.timestamp}`,
        'info',
        event.swarm.teamName
          ? `Swarm updated: ${event.swarm.teamName}.`
          : 'Swarm updated.',
        event.timestamp,
      );
    case 'swarm_event':
      return createEventLog(
        `swarm-event-${event.sessionId}-${event.payload.kind}-${event.timestamp}`,
        'info',
        [
          event.payload.swarm.teamName || 'Swarm',
          event.payload.taskTitle?.trim() || event.payload.toolName?.trim() || event.payload.kind,
        ]
          .filter(Boolean)
          .join(' · '),
        event.timestamp,
      );
    case 'agent_event':
      return createEventLog(
        `agent-event-${event.sessionId}-${event.payload.kind}-${event.timestamp}`,
        'info',
        [
          event.payload.agentName || event.payload.agentId || 'Agent',
          event.payload.taskTitle?.trim() || event.payload.detail?.trim() || event.payload.kind,
        ]
          .filter(Boolean)
          .join(' · '),
        event.timestamp,
      );
    case 'model_switched':
      return createEventLog(
        `model-switched-${event.sessionId}-${event.timestamp}`,
        'warn',
        `Model switched to ${event.model}.`,
        event.timestamp,
      );
    case 'permission_mode_changed':
      return createEventLog(
        `permission-mode-${event.sessionId}-${event.timestamp}`,
        'info',
        `Permission mode: ${event.mode}.`,
        event.timestamp,
      );
    case 'interrupted':
      return createEventLog(
        `interrupted-${event.sessionId}-${event.timestamp}`,
        'warn',
        'Execution interrupted.',
        event.timestamp,
      );
    case 'error':
      return createEventLog(
        `error-${event.sessionId}-${event.timestamp}`,
        'error',
        event.error,
        event.timestamp,
      );
    default:
      return null;
  }
}

function eventLogFromRegistryEvent(event: RuntimeRegistryEvent): EventLog | null {
  if (event.type === 'registered') {
    return createEventLog(
      `registered-${event.sessionId}-${event.timestamp}`,
      'info',
      'Session registered in runtime.',
      event.timestamp,
    );
  }

  if (event.type === 'unregistered') {
    return createEventLog(
      `unregistered-${event.sessionId}-${event.timestamp}`,
      'warn',
      'Session closed in runtime.',
      event.timestamp,
    );
  }

  return event.event ? eventLogFromRuntimeEvent(event.event) : null;
}

function getSnapshotFromRuntimeEvent(
  event: RuntimeEvent | undefined,
): RuntimeSessionSnapshot | undefined {
  if (!event) {
    return undefined;
  }

  if (event.type === 'session_started' || event.type === 'session_updated') {
    return event.snapshot;
  }

  return undefined;
}

export function appendEventToSession(
  previousSessions: Session[],
  sessionId: string,
  event: EventLog,
): Session[] {
  return previousSessions.map(session => {
    if (session.id !== sessionId) {
      return session;
    }

    if (session.events.some(existing => existing.id === event.id)) {
      return session;
    }

    return {
      ...session,
      events: [event, ...session.events].slice(0, 40),
      updatedAt: event.timestamp,
    };
  });
}

export function applyRuntimeRegistryEvent(
  previousSessions: Session[],
  event: RuntimeRegistryEvent,
): Session[] {
  if (event.type === 'unregistered') {
    return previousSessions.filter(session => session.id !== event.sessionId);
  }

  let nextSessions = previousSessions;

  const snapshotFromEvent =
    event.snapshot ||
    (event.type === 'runtime_event' ? getSnapshotFromRuntimeEvent(event.event) : undefined);

  if (snapshotFromEvent) {
    const previousSession = previousSessions.find(session => session.id === event.sessionId);
    const nextSession = createBaseSession(snapshotFromEvent, previousSession, event.timestamp);
    const sessionMap = new Map(previousSessions.map(session => [session.id, session]));
    sessionMap.set(event.sessionId, {
      ...nextSession,
      messages: previousSession?.messages || [],
      swarm: previousSession?.swarm || nextSession.swarm,
      events: previousSession?.events || [],
      rawDetail: previousSession?.rawDetail,
    });
    nextSessions = sortSessions([...sessionMap.values()]);
  }

  const log = eventLogFromRegistryEvent(event);
  return log ? appendEventToSession(nextSessions, event.sessionId, log) : nextSessions;
}

export function applyRuntimeSessionEvent(
  previousSessions: Session[],
  sessionId: string,
  event: RuntimeEvent,
): Session[] {
  let nextSessions = previousSessions;
  const previousSession = previousSessions.find(session => session.id === sessionId);

  if (event.type === 'session_started' || event.type === 'session_updated') {
    const nextSession = createBaseSession(event.snapshot, previousSession, event.timestamp);
    const sessionMap = new Map(previousSessions.map(session => [session.id, session]));
    sessionMap.set(sessionId, {
      ...nextSession,
      messages: previousSession?.messages || [],
      swarm: previousSession?.swarm || nextSession.swarm,
      events: previousSession?.events || [],
      rawDetail: previousSession?.rawDetail,
    });
    nextSessions = sortSessions([...sessionMap.values()]);

    if (event.snapshot.status === 'running') {
      nextSessions = ensureStreamingThinkingPlaceholder(
        nextSessions,
        sessionId,
        event.timestamp,
      );
    }
  }

  if (event.type === 'thinking_started') {
    nextSessions = ensureStreamingThinkingPlaceholder(
      nextSessions,
      sessionId,
      event.timestamp,
    );
  }

  if (event.type === 'thinking_delta') {
    nextSessions = upsertStreamingMessage(nextSessions, sessionId, {
      streamKind: 'thinking',
      delta: event.delta,
      timestamp: event.timestamp,
    });
  }

  if (event.type === 'thinking_completed') {
    nextSessions = clearStreamingMessage(nextSessions, sessionId, 'thinking');
  }

  if (event.type === 'message_delta') {
    nextSessions = upsertStreamingMessage(nextSessions, sessionId, {
      streamKind: 'response',
      delta: event.delta,
      timestamp: event.timestamp,
    });
  }

  if (event.type === 'message_completed') {
    nextSessions = clearStreamingMessage(nextSessions, sessionId, 'thinking');
    const message = mapRawRuntimeMessageToUi(event.message);
    if (message) {
      nextSessions = appendMessageToSession(nextSessions, sessionId, message);
    }
  }

  if (event.type === 'permission_mode_changed') {
    nextSessions = nextSessions.map(session =>
      session.id === sessionId
        ? {
            ...session,
            permissionMode: event.mode,
            updatedAt: event.timestamp,
          }
        : session,
    );
  }

  if (
    (event.type === 'session_started' || event.type === 'session_updated') &&
    previousSession &&
    previousSession.activeChannel !== event.snapshot.activeChannel
  ) {
    nextSessions = appendEventToSession(
      nextSessions,
      sessionId,
      createEventLog(
        `channel-claimed-${sessionId}-${event.timestamp}`,
        'info',
        `Canal activo: ${event.snapshot.activeChannel === 'web-ui' ? 'Web UI' : 'CLI'}.`,
        event.timestamp,
      ),
    );
  }

  if (event.type === 'interrupted' || event.type === 'error') {
    nextSessions = clearPendingMessagesFromSession(nextSessions, sessionId);
  }

  if (event.type === 'interrupted') {
    nextSessions = appendMessageToSession(
      nextSessions,
      sessionId,
      createSystemRuntimeMessage(
        sessionId,
        'Auto cancelado por el usuario.',
        event.timestamp,
      ),
    );
  }

  const log = eventLogFromRuntimeEvent(event);
  return log ? appendEventToSession(nextSessions, sessionId, log) : nextSessions;
}
